### ISSUE TITLE
[Question] Potential incorrect test case

### ISSUE THREAD

**Issue by Holi0317** [CastleLab/COMP3021-2020Fall-PA1-Student-Version#1]
Hi,

I've got an issue with the provided test case and suspect the test case is incorrect.

From the README.md specification, we have got the following win rules:

> Be the first one to move a **knight** (not other type of pieces) to the central square of the gameboard and then leave the central square...

There is one test case bundled in the starter pack covers this requirement, [testWinByLeaveCentralPlace](https://github.com/CastleLab/COMP3021-2020Fall-PA1-Student-Version/blob/13d8757f08c9e424dd19b0d959c294d9b2dfde3e/src/test/java/castle/comp3021/assignment/protocol/GameUnitTests.java#L100).

However, the test case fulfill the "enter center then leave" requirement using a piece with type ``MockPiece``. Which does not looks like a Knight in any sense.

Currently I am using ``instanceof Knight`` for check the piece is a knight before doing leaving the center checking. Replacing ``MockPiece`` with ``Knight`` in the test case would pass the test. Or removing the ``instanceof`` condition in the code will make the test pass. But that means any piece leaving the center result in win.

So I would like to ask if the test case needs to be fixed or winning condition does not requires a knight. Thanks

**Comment by Troublor** [comment]
Thanks. That is a real problem. The truth is, initially in the assignment specification we do not have the requirement that the game must be won by a Knight, so the test for winning rule is designed using `MockPiece`. After updating the requirement, the test is forgotten. 

Will fix it in a PR and send an email to illustrate this problem to all the students. Well done.

**Comment by Troublor** [comment]
@Holi0317 A PR #2 fixing this issue has been merged. Please check if the issue still exists or not.

**Comment by Holi0317** [comment]
Yes the patch makes my code passes all tests. Thanks.
