### ISSUE TITLE
[Question]About mockPiece

### ISSUE THREAD

**Issue by leiyi777** [CastleLab/COMP3021-2020Fall-PA1-Student-Version#10]
In checking the winner, we need to check the Piece is whether a Knight or Archer by using their labels.
However, in the test part, the mockPiece labels 'M' to pass the provided test, we need consider the mockPiece. 
I am wondering in the TA-only integrated tests if there are any other pieces label?
Can I just use the label 'K' and label 'M' to check the wining condition? Like only Knight and mockPiece passing the central place is regarded as a win.

**Comment by Troublor** [comment]
Only Knight can win the game by leaving central place. So you can just use `instanceof Knight` condition when implementing `getWinner()`.

**Comment by leiyi777** [comment]
Thank you so much!
