### ISSUE TITLE
About updateScore

### ISSUE THREAD

**Issue by pcwchau** [CastleLab/COMP3021-2020Fall-PA1-Student-Version#12]
As stated in javaDoc, we need to update the score of a player according to the Piece. But the score is only calculated based on the Manhattan distance, so why is it related to the Piece?

**Comment by Troublor** [comment]
It is because we may use another scoring scheme in the assignments afterwards. For now in PA1, we just calculate it based on the move of Manhattan distance.

**Comment by pcwchau** [comment]
Does that means we can simply ignore the Piece in updateScore now?

**Comment by Troublor** [comment]
Yes you can in PA1.
