### ISSUE TITLE
[Question] Potential Glitch in PA1_obfuscated.jar

### ISSUE THREAD

**Issue by lky-bulbasaur** [CastleLab/COMP3021-2020Fall-PA1-Student-Version#13]
In PA1_obfuscated.jar, **the human (white) player can move both black and white pieces**. For example, the human (white) player can move a black piece in the first round, then move a white piece in the second round. If the human (white) player wins a game using a black knight, PA1_obfuscated.jar announces white (human) as the winner.

I would like to know if this feature is intentional or not. I also would like to know if we should also consider **a player moving a piece that does not belong to them** an invalid move.

Thank you in advance for looking into this matter.

**Comment by Troublor** [comment]
There is indeed a bug in the obfuscated version that human player can move the enemy's pieces. A player should not move a piece that does not belong to him.
