### ISSUE TITLE
About importing java.util.* in ConsolePlayer.java

### ISSUE THREAD

**Issue by Chen-Mengqi** [CastleLab/COMP3021-2020Fall-PA1-Student-Version#14]
The requirement of this part of assignment needs the data from console, but we cannot input the data to the console without importing other libraries.  So I write import java.util.*; at the top of the java file (out of the range of // TODO student implementation). So will I get a score deduction by this? If I will, is there other way to input the data without importing other libraries? Thank you.

**Comment by Troublor** [comment]
You can always import libraries as you wish. Don't worry.
