### ISSUE TITLE
Question about getWinner(lastPlayer, lastPiece, lastMove);

### ISSUE THREAD

**Issue by JJTam** [CastleLab/COMP3021-2020Fall-PA1-Student-Version#15]
The three parameters are all referring to the last player, but how can I get the lastMove made by the lastPlayer in Method -- Player start()? Can I have some hints?

**Comment by Troublor** [comment]
Usually the workflow in `start()` would be:
1.  Ask player to make a move
2.  Perform the move on the gameboard
3.  Check the winner
4.  If no winner, ask the next player. 

You see, the last move is the move you get from step 1.

**Comment by JJTam** [comment]
Oh, I see. The last move, last player, last piece are all as same as the current player, piece, move right? But you describe it as the "last" in the description in Method getWinner(), that I think "last" is the last player who has taken his turns (eg: current turns = console player, last turns = computer player ). So I am so confused.

**Comment by Troublor** [comment]
"last" move is the latest move made by "last" player. It refers to the player and the move in the Step 1 as I stated above.
