### ISSUE TITLE
About Winning Condition

### ISSUE THREAD

**Issue by pcwchau** [CastleLab/COMP3021-2020Fall-PA1-Student-Version#18]
As stated:

> within the first numMovesProtection number of moves, the following things are not allowed:
> win the game

Does this "win the game" include scenarios like "Capture all the pieces of the other player" and "no available moves "?

For example, if in the first round, there is already no availabe move, will the current player win immediately?
Also, if in the first round, one player has no pieces, will the other player win immediately?

**Comment by Troublor** [comment]
It means within the protected moves, player cannot win by moving a piece out of central place. I will update the specification to avoid misunderstanding. Thanks for pointing out.

**Comment by pcwchau** [comment]
would it be possible that in the first round, one player does not have any pieces?

**Comment by Troublor** [comment]
I don't think it's possible. The initial piece placement on board is defined in `initialBoard` in `Configuration`, which can be any layout but not empty. 

Despite the `initialBoard` in `Configuration` can be anything, we have a requirement on the game configuration inside `createGame()`. Make sure to be consistent to the specification.
