### ISSUE TITLE
[Question]Case recognition of input move

### ISSUE THREAD

**Issue by ywucr** [CastleLab/COMP3021-2020Fall-PA1-Student-Version#19]
I noticed that in demo project both capital and small letter move input can be recognized.
However as the guide we should only recognize small letter input. 
I want to know does it matter in this case recognition part?
![small](https://user-images.githubusercontent.com/56708723/94533190-6e4c8280-0271-11eb-98fc-ca3b5b195e8f.png)
![capital](https://user-images.githubusercontent.com/56708723/94533205-73a9cd00-0271-11eb-9ac5-f8fc9bc2c165.png)
Thank you!

**Comment by Troublor** [comment]
Your program should be case insensitive. `A1->B3` is also valid move.
