### ISSUE TITLE
Question on the Scanner class in ConsolePlayer.java

### ISSUE THREAD

**Issue by wongtszchun** [CastleLab/COMP3021-2020Fall-PA1-Student-Version#21]
If I don't use close() in the user input for the Scanner object in ConsolePlayer.java, will there be any problem? 
Because I used close() before returning the next move.
It is fine in the first move of the console player but in the next round of console player (user inputs again for his/her next move), the program crash. When I removed the close();, the program run without errors.

**Comment by Troublor** [comment]
Could you share your code and the corresponding error?

**Comment by wongtszchun** [comment]
code:

    public @NotNull Move nextMove(Game game, Move[] availableMoves) {
        Scanner sc = new Scanner(System.in);
        String input;
        while (true) {
            System.out.print("Input your move: ");
            input = sc.nextLine();
            
            //skipped some details here

            if(found) {         //found in availableMove then return
                sc.close();
                return nextMove;      
            }
    }
}

error:
Exception in thread "main" java.util.NoSuchElementException: No line found
	at java.base/java.util.Scanner.nextLine(Scanner.java:1651)
	at castle.comp3021.assignment.player.ConsolePlayer.nextMove(ConsolePlayer.java:54)
	at castle.comp3021.assignment.JesonMor.start(JesonMor.java:67)
	at castle.comp3021.assignment.Main.main(Main.java:84)

if i don't use sc.close();, there will be no error

**Comment by Troublor** [comment]
The `close` method will close `System.in` stream. We don't want to close the `System.in` since we will use it later for next player. Check this [StackOverflow](https://stackoverflow.com/questions/26245468/what-does-scanner-close-do) post for more explanation. 

So you don't need to close the scanner before the return of `nextMove` method.

**Comment by wongtszchun** [comment]
Got it, Thank you!!
