### ISSUE TITLE
Questions about updateScore

### ISSUE THREAD

**Issue by wytangae** [CastleLab/COMP3021-2020Fall-PA1-Student-Version#22]
According to the commit [here](https://github.com/CastleLab/COMP3021-2020Fall-PA1-Student-Version/commit/5920767ce6bcfbc7d4012e993a5ed709f2b362d5), does it mean that we must remove all validation implermented and all addition tests related to invalid moves before submission?

Also, do we have to update the comment to sync with the commits made in this repository (CastleLab / COMP3021-2020Fall-PA1-Student-Version) after the .zip in the [Release Section](https://github.com/CastleLab/COMP3021-2020Fall-PA1-Student-Version/releases/tag/PA1_release) being downloaded?

Thank you!.

**Comment by wytangae** [comment]
In addition, in that the case that range checks are also not needed? Thank you.

**Comment by Troublor** [comment]
What do you mean range checks? 

Please do not do validation in `updateScore`, since the move passed to `updateScore` must be valid. 
 
You don't need to update the comment.

**Comment by wytangae** [comment]
Since my downloaded version from Release contains the old documentation, so I just noticed this change now while checking the commit history of this repository.

**Comment by Troublor** [comment]
It doesn't matter if you didn't update the latest changes.

**Comment by wytangae** [comment]
since that old documentation still contains the line "Student should make NO assumption that the {@link Move} is valid." so I think I should at least comment out the codes related to validation only as I had followed that documentation.
