### ISSUE TITLE
Question about Tie Breaker Test

### ISSUE THREAD

**Issue by Xelopie** [CastleLab/COMP3021-2020Fall-PA1-Student-Version#3]
If I get the rule correctly, the tie breaker thing should only be triggered when the player who is gonna move next has no available move, right?
![image](https://user-images.githubusercontent.com/47631876/93967387-ac413680-fd99-11ea-81bb-0008f75af8d7.png)
I got this situation at last after running the tie breaker test and I don't see how it is gonna trigger the tie breaker thing.
Is the test case provided wrong or am I misunderstanding?

**Comment by Troublor** [comment]
You can set the color of each player in the test when constructing player object. 
```java
var player1 = new MockPlayer(Color.GREEN);
var player2 = new MockPlayer(Color.BLUE);
```

And you will see currently it's player2's turn, but his two pieces (b1 and c3) have no available moves.

**Comment by Xelopie** [comment]
Isn't b1->a3 or c3->a2 an available move?
![image](https://user-images.githubusercontent.com/47631876/93968251-c67c1400-fd9b-11ea-90e0-465bae15c526.png)

**Comment by Troublor** [comment]
That will violate the block rule of Knights. See rules [here](https://en.wikipedia.org/wiki/Xiangqi#Horse). Note that in PA1, we are using the moving rule of Knight s Horses) in Chinese Chess.

**Comment by Xelopie** [comment]
OK got it, thanks!
