### ISSUE TITLE
About move with protection

### ISSUE THREAD

**Issue by Xelopie** [CastleLab/COMP3021-2020Fall-PA1-Student-Version#4]
> Moves with Protection
> There is a field of Configuration class called numMovesProtection which represents that within the first numMovesProtection number of moves, the following things are not allowed:
> 
> 1. capture the enemy's pieces
> 2. win the game

The moves with protection rule said that winning is not allowed in the first N rounds. Does that mean any move that will cause "winning" is not allowed? (move into central place and move out) Or it just doesn't allow the player to win even if they move out from central place?

**Comment by Troublor** [comment]
The latter statement is true. Within the first N moves (total number of moves by two players), players can move piece in and out of the central place, but this just doesn't result in him winning the game.

**Comment by Xelopie** [comment]
Alright! Thanks for the clarification

**Comment by Xelopie** [comment]
What if player doesn't have an available move but it is still in move protection rounds? What behavior are we expecting?

**Comment by Troublor** [comment]
Tie breaking rule is not subject to the protection rounds. If within N protected moves, there is no available moves to make, the winner will birth according to the tie breaking rule.

**Comment by Xelopie** [comment]
Great! Thanks
