### ISSUE TITLE
[Question] Regarding Grading Scheme

### ISSUE THREAD

**Issue by lky-bulbasaur** [CastleLab/COMP3021-2020Fall-PA1-Student-Version#7]
PA1's Grading Scheme suggests that **"Pass all sample tests"** gives 10% of total marks and **"Pass all TA-only integrated tests"** gives 30% of total marks, but their respective remarks suggest otherwise. I would like to know if there are any errors in the Grading Scheme.

Thank you in advance for looking into this matter.

**Comment by Troublor** [comment]
I don't think there is any error. Sample tests and TA-only tests are two different, separate sets of tests.

**Comment by lky-bulbasaur** [comment]
The Grading Scheme suggests the score for Pass all sample tests **(10%)** is calculated as (# of passed tests / # of sample tests) * **30%**.

But the score for Pass all TA-only integrated tests **(30%)** is calculated as (# of passed tests / # of integrated tests) * **10%**.

The stated percentages and the percentage used in the score calculation are different, so I was confused. Perhaps there were some typos in the Grading Scheme?

Thank you in advance for looking into this matter.

**Comment by Troublor** [comment]
Right there is a typo. Just fixed. Thank you.
