### ISSUE TITLE
[Question]About method movePiece()

### ISSUE THREAD

**Issue by leiyi777** [CastleLab/COMP3021-2020Fall-PA1-Student-Version#8]
For method movePiece() in JesonMor class, I call the addInitialPiece() method in Configuration class to modify the place of the piece and it needs to set the piece of the source place to null. However, the addInitialPiece() method does not check the Null input and it may cause the java.lang.NullPointerException.
I am asking if I can modify the addInitialPiece() method or not since this method has already been implemented for us.
Or am I doing wrong in this part?

**Comment by Troublor** [comment]
`addInitialPiece()` should be only used before constructing the `JesonMor` object, which is meant for setting the inital placement of pieces of each player. The initial placement set by `addInitialPiece()` is only used in the constructor of `Game` object. It should not be called afterwards.

**Comment by leiyi777** [comment]
Thank you so much!
